### ISSUE TITLE
how can i add more recipes

### ISSUE THREAD

**Issue by Khalcifer22** [nicolas-lang/Factorio.SpaceScienceDelivery#9] opened 2022-05-03 12:45 UTC
How can i add more recipes in Space Science Delivery

**Comment by nicolas-lang** [comment] 2022-05-03 20:27
Science-packs should be added automaically. If they aren't it can probably be fixed with a optional dependancy on the adding mod in modinfo.json.

Please provide more information.

**Comment by Khalcifer22** [comment] 2022-05-08 18:32
Hi, i want add more recipes, because i can send only vanilla science pack

**Comment by nicolas-lang** [comment] 2022-05-08 18:56
Which mod's science packs are you not seeing ?

_All mods science packs shoudl be displayed automatically unless there is an issue with the mod's loading order (which means, adding the packs after Space Science Delivery already completed processing)_
I can probably fix that but I need to reproduce the issue.

**Comment by Khalcifer22** [comment] 2022-05-09 16:13
I can see only from vanilla, but for SE nope

https://mods.factorio.com/mod/space-exploration

**Comment by nicolas-lang** [comment] 2022-05-09 16:19
oh, that shouldn't happen - I'll check next weekend

**Comment by nicolas-lang** [comment] 2022-05-09 16:33
After a bit of re-thinking - that is 100% the intended behavior for SE, the SE-Space specific science packs can only be crafted in space, and the intention for this mod is to allow "vanilla science packs" and "non-SE/modded science packs" to be crafted on the surface and then being delivered to space by cannon.

**Closed as completed by nicolas-lang** 2022-05-09 16:33 UTC
Labels: wontfix

**Comment by nicolas-lang** [comment] 2022-05-09 16:34
Feed free to explain why you would expect it to work differently. I might change it If you can provide a valid argument.
